# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff0d2078a112b5c6df46243eb2cb80d7d466083b51b01d53fcc8eaf84ecedbf6e122ee21713cac35ed6e5785d907b6d10f6f58125551359afe50fa8802f7a881

test:
  secret_key_base: e6203946fa687e14c4f2179bcaea5b5b0419557c46fa4a20a6039857f8394fea6a62aa5cc78636717b855f61285f0b666d0d2ab6a19e96d9a9bbd08d596fb737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
